#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyS/Y6SKlhe02KZ/jFAKDCw3Rv5znSlTeTvI/qXMYtCi5HvO7COVXgpvkA0SROwgj6pVlFzZOM+0UsY+2NkYJ00sCZsHVOWMI7vzpbu6z3OUCfqjK/pc1vEXjh0gLNfOisUdL1qaWIBphrMa7IUSquWHavPlNI7vb+g/Dl3jDT4cCuADWhbt+dqQYBh8U10u/NIP/R8mvJCJ+o5tpi+NlIVkuv6uzoOHIaMGlBqFpr7uQMYcZV5ws3PwdIZfuw19BIAXp90gnr9ujf1xY/vEpxPMHP0zrG8XUd0HZ4aEKfTfcDaq0xIlIMC6wiEj3ybE52+WxP9vidt9Kp00xp7nMVta1GT5j/hF/WXdw3OQAKdLSpZYZinpcI323ouiUUREH1VHNOtUWYwpinwZBGQU2R4aUuTmGoUVbzqs8/+Jf/Ts72OV/FHxqb8tvfpiO+C7PKGGwBhioChRmeFLmq0M704ACsyFLmxKF4haJjEZ3rWF856GczRCX+Hur0FEcVg/CYPEADgI9vvDSqTpZfqAwtK9lx4Tk4SVzGZYSnljtvhlmEc5+14b4xXrCNY5M1EfPEcvDqEup8Ci7Ng3WSrY9FopccMschBiq1laQ99UvdDTMOwnDjd5Mz/NMqdJT4BJetgFpdLublQvPD49d+YiHYL9BWiOdnKflZlqmQjMmGQw== bchoy@jwplayer.com

write_files:
  - path: /cloud-config.yml
    permissions: "0700"
    owner: root
    content: |
      #cloud-config
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyS/Y6SKlhe02KZ/jFAKDCw3Rv5znSlTeTvI/qXMYtCi5HvO7COVXgpvkA0SROwgj6pVlFzZOM+0UsY+2NkYJ00sCZsHVOWMI7vzpbu6z3OUCfqjK/pc1vEXjh0gLNfOisUdL1qaWIBphrMa7IUSquWHavPlNI7vb+g/Dl3jDT4cCuADWhbt+dqQYBh8U10u/NIP/R8mvJCJ+o5tpi+NlIVkuv6uzoOHIaMGlBqFpr7uQMYcZV5ws3PwdIZfuw19BIAXp90gnr9ujf1xY/vEpxPMHP0zrG8XUd0HZ4aEKfTfcDaq0xIlIMC6wiEj3ybE52+WxP9vidt9Kp00xp7nMVta1GT5j/hF/WXdw3OQAKdLSpZYZinpcI323ouiUUREH1VHNOtUWYwpinwZBGQU2R4aUuTmGoUVbzqs8/+Jf/Ts72OV/FHxqb8tvfpiO+C7PKGGwBhioChRmeFLmq0M704ACsyFLmxKF4haJjEZ3rWF856GczRCX+Hur0FEcVg/CYPEADgI9vvDSqTpZfqAwtK9lx4Tk4SVzGZYSnljtvhlmEc5+14b4xXrCNY5M1EfPEcvDqEup8Ci7Ng3WSrY9FopccMschBiq1laQ99UvdDTMOwnDjd5Mz/NMqdJT4BJetgFpdLublQvPD49d+YiHYL9BWiOdnKflZlqmQjMmGQw== bchoy@jwplayer.com
      mounts:
       - ["/dev/vdb1", "/mnt", "ext4", ""] 
      rancher:
        services:
          rancher-server:
            image: rancher/server:stable
            ports:
              - 80:8080
            restart: always
            volumes:
              - /mnt/rancher-server-mysql:/var/lib/mysql
        network:
          dns:
            nameservers:
            - 8.8.8.8
            - 8.8.4.4
        services_include:
          ubuntu-console: true
        state:
          fstype: auto
          dev: LABEL=RANCHER_STATE
          autoformat:
            - /dev/vda
  - path: /opt/rancher/bin/start.sh
    permissions: "0700"
    owner: root
    content: |
      #!/bin/bash
      echo y | ros install -f -c /cloud-config.yml -d /dev/vda
